name: CI/CD
on:
    push:
        branches: [main, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            maven_repository: https://maven.pkg.github.com/${{ github.repository }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download and tar java 5 file
              run: |
                 chmod +x jdk-1_5_0_22-linux-amd64.bin 
                 ./jdk-1_5_0_22-linux-amd64.bin > /dev/null < <(echo yes)
                 tar -czf java-package.tar.gz ./jdk1.5.0_22

            - name: Setup Java 5 using tar file
              uses: actions/setup-java@v4
              with:
                distribution: 'jdkfile'
                java-version: '1.5'
                jdkFile: ${{ github.workspace}}/java-package.tar.gz
                architecture: x64
            
            - name: Verify Java version
              run: java -version
            
            - name: Install apache ant 1.8.4
              run: |
                wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.8.4-bin.tar.gz \
                && tar -xzf ./apache-ant-1.8.4-bin.tar.gz -C /opt/ \
                && ln -s /opt/apache-ant-1.8.4 /opt/ant 

            - name: Update PATH with Ant
              run: |
                echo "ANT_HOME=/opt/ant" >> $GITHUB_ENV
                echo "PATH=$PATH:$ANT_HOME/bin" >> $GITHUB_ENV

            
            - name: Verify Ant version
              run: ant -version
            
            - name: Build with Ant
              run: |
                ant clean compile
               
            
            
            - name: Run Application
              run: ant run

            - name: generate jar file
              run: |
               ant build-jar
            # - name: Generate pom.xml file
            #   run: |
            #     cat <<\EOF >> pom.xml
            #     <?xml version="1.0" encoding="UTF-8"?>
            #     <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            #         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            #         <modelVersion>4.0.0</modelVersion>
            #         <groupId>org.example</groupId>
            #         <artifactId>hello-world</artifactId>
            #         <version>1.0-SNAPSHOT</version>
            #         <properties>
            #             <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            #         </properties>
            #         <plugins>
            #         <plugin>
            #         <groupId>org.apache.maven.plugins</groupId>
            #         <artifactId>maven-compiler-plugin</artifactId>
            #         <version>3.1</version>
            #         </plugin>
            #         <plugin>
            #             <groupId>org.apache.maven.plugins</groupId>
            #             <artifactId>maven-toolchains-plugin</artifactId>
            #             <version>1.1</version>
            #             <executions>
            #               <execution>
            #                 <goals>
            #                   <goal>toolchain</goal>
            #                 </goals>
            #               </execution>
            #             </executions>
            #             <configuration>
            #               <toolchains>
            #                 <jdk>
            #                   <version>17</version>
            #                   <vendor>openjdk</vendor>
            #                 </jdk>
            #               </toolchains>
            #             </configuration>
            #           </plugin>
            #           </plugins>
            #         <distributionManagement>
            #           <repository>
            #             <id>github</id>
            #             <name>GitHub OWNER Apache Maven Packages</name>
            #             <url>${{env.maven_repository}}</url>
            #           </repository>
            #         </distributionManagement>
            #         </project>
            #     EOF
            # - name: Generate toolchains.xml file
            #   run: |
            #     cat <<\EOF >> toolchains.xml
            #     <?xml version="1.0" encoding="UTF-8"?>
            #     <toolchains>
            #       <toolchain>
            #       <type>jdk</type>
            #       <provides>
            #         <version>17</version>
            #         <vendor>openjdk</vendor>
            #       </provides>
            #       <configuration>
            #         <jdkHome>/opt/hostedtoolcache/Java/17.0.2</jdkHome>
            #       </configuration>
            #     </toolchain>

            # - name: Setup Java
            #   uses: actions/setup-java@v4
            #   with:
            #     distribution: 'temurin'
            #     java-version: '17'

            # - name: Verify new Java version
            #   run: java -version

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: hello-world
                path: war/lib/helloworld.jar
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        env:
          maven_repository: https://maven.pkg.github.com/${{ github.repository }}
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write

        steps:
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: hello-world

          # - name: Generate settings.xml file
          #   run: |
          #       cat <<\EOF >> settings.xml
          #       <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          #         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          #         xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd" >
          #         <servers>
          #           <server>
          #             <id>github</id>
          #             <username>${{ github.actor }}</username>
          #             <password>${{ secrets.GITHUB_TOKEN }}</password>
          #              <configuration>
          #               <httpHeaders>
          #                 <property>
          #                   <name>Authorization</name>
          #                   <value>Bearer ${{ secrets.GITHUB_TOKEN }}</value>
          #                 </property>
          #               </httpHeaders>
          #             </configuration>
          #           </server>
          #         </servers>
          #         <profiles>
          #         <profile>
          #           <id>github</id>
          #           <repositories>
          #             <repository>
          #               <id>github</id>
          #               <url>https://maven.pkg.github.com/${{ github.repository }}</url>
          #               <snapshots>
          #                 <enabled>true</enabled>
          #               </snapshots>
          #             </repository>
          #           </repositories>
          #         </profile>
          #       </profiles>

          #       <activeProfiles>
          #         <!-- Ativar o perfil para o GitHub Packages -->
          #         <activeProfile>github</activeProfile>
          #       </activeProfiles>
          #       </settings>
          #       EOF
          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '17'
              server-id: github
              settings-path: ${{ github.workspace }}
            

          - name: Generate pom.xml file
            run: |
                cat <<\EOF >> pom.xml
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example</groupId>
                    <artifactId>hello-world</artifactId>
                    <version>1.0-SNAPSHOT</version>
                    <properties>
                        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                    </properties>
                    
                    <distributionManagement>
                      <repository>
                        <id>github</id>
                        <name>GitHub OWNER Apache Maven Packages</name>
                        <url>${{env.maven_repository}}</url>
                      </repository>
                    </distributionManagement>
                    </project>
                EOF

          - name: Maven settings
            uses: s4u/maven-settings-action@v3.0.0
            with:
              servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}", "configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GITHUB_TOKEN }}"}}}}]'
          - name: verify maven version
            run: mvn -version
          
          - name: deploy package
            run: mvn deploy
          # - name: deploy package
          #   run: mvn clean source:jar deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -DdeployAtEnd=true -Dmaven.source.includePom=true -Dmaven.install.skip=true
            
        